### ISSUE TITLE
Using the example I have this error

### ISSUE THREAD

**Issue by tayeb83** [daugaard/scikit-learn-from-ruby#1]
/usr/local/lib/ruby/gems/2.4.0/gems/pycall-1.0.3/lib/pycall/import.rb:46:in `import_module’: : dlopen(/Users/tay/anaconda3/lib/python3.6/site-packages/scipy/sparse/linalg/isolve/_iterative.cpython-36m-darwin.so, 2): Symbol not found: _main (PyCall::PyError)

Thanks

**Comment by daugaard** [comment]
Try to run the tutorial.py script using python and let me know what that outputs.

**Comment by tayeb83** [comment]
Thanks,
 The problem is corrected, the issue was an conda issue.

https://github.com/conda-forge/opencv-feedstock/issues/69

regards,
TM

**Comment by daugaard** [comment]
Okay great! I am happy you figured it out.
